name: 'Build Infrastructure'

on:
  push:
    branches: [ "*" ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - '.github/workflows/**'

permissions:
  contents: read

jobs:
  build:
    name: 'Build Environment'
    runs-on: ubuntu-latest
    #environment: production

    defaults:
      run:
        shell: bash
        working-directory: ./backend/terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v3

    # Set TF_WORKSPACE environment variable
    - name: Set TF_WORKSPACE
      run: |
        if [[ github.ref == 'refs/heads/main' ]]; then
          echo "TF_WORKSPACE=${{ vars.PROD_WORKSPACE }}" >> $GITHUB_ENV
        else
          echo "TF_WORKSPACE=${{ vars.TEST_WORKSPACE }}" >> $GITHUB_ENV
        fi

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: terraform init
      timeout-minutes: 5

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      run: terraform fmt -check
      timeout-minutes: 5

    # Generates an execution plan for Terraform
    - name: Terraform Plan
      run: terraform plan
      timeout-minutes: 10
      env:
        TF_INPUT: false
        TF_WORKSPACE: ${{ env.TF_WORKSPACE }}

    # On push to any branch other than "main", apply changes to Test environment
    - name: Terraform Apply to Test Environment
      if: github.ref != 'refs/heads/main' && github.event_name == 'push'
      run: |
        # Add your deployment commands for the test environment here
      env:
        TF_INPUT: false
        TF_WORKSPACE: ${{ env.TF_WORKSPACE }}

    # On push to "main", apply changes to Prod environment
    - name: Terraform Apply to Prod Environment
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve
      env:
        TF_INPUT: false
        TF_WORKSPACE: ${{ env.TF_WORKSPACE }}
        
  close_pull_request_job:
    name: 'Close Pull Request Job'
    if: github.event_name == 'pull_request' && github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Close Pull Request
        id: closepullrequest
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          action: "close"
