name: 'Deploy Site'

on:
  workflow_dispatch:
    permissions:
      users:
        - noconnor29
jobs:
  deploy_azure_static_web_app:
    runs-on: ubuntu-latest
    name: 'Deploy Web App'
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true
      - name: Deploy
        id: deploy_web_app
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }} # Used for Github integrations (i.e. PR comments)
          action: "upload"
          ###### Repository/Build Configurations - These values can be configured to match your app requirements. ######
          # For more information regarding Static Web App workflow configurations, please visit: https://aka.ms/swaworkflowconfig
          app_location: "/frontend" # App source code path
          #api_location: "/backend/api" # Api source code path - optional
          #output_location: "" # Built app content directory - optional
          ###### End of Repository/Build Configurations ######
    #needs: build
